table 'Regional NM & ACH inputs by tea'
	lineageTag: 0ae1f696-1737-415d-b4d7-bc6ebeb86491

	column Date
		dataType: dateTime
		formatString: Long Date
		lineageTag: 36d410fb-4ee2-4425-9eb6-39098885f3ed
		summarizeBy: none
		sourceColumn: Date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Ops Team Currency'
		dataType: string
		lineageTag: dedad9b7-4014-4a02-8ff2-84309ffcc78b
		summarizeBy: none
		sourceColumn: Ops Team Currency

		annotation SummarizationSetBy = Automatic

	column 'Queue Input Count'
		dataType: int64
		formatString: 0
		lineageTag: 6ac37e97-8994-4196-944f-fa5c5a0f3d8e
		summarizeBy: sum
		sourceColumn: Queue Input Count

		annotation SummarizationSetBy = Automatic

	partition 'Regional NM & ACH inputs by tea' = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents("C:\Users\user\Documents\Pay Ops BI Lead Homework_Answer(AutoRecovered).xlsx"), null, true),
				    Table5_Table = Source{[Item="Table5",Kind="Table"]}[Data],
				    #"Changed Type" = Table.TransformColumnTypes(Table5_Table,{{"Ops Team Currency", type any}, {"APAC Expansion ops", type any}, {"APAC Mature ops", type any}, {"Emerging ops", type any}, {"EUR ops", type any}, {"Europe ops", type any}, {"GBP ops", type any}, {"JPYKRW ops", type any}, {"NorthAm ops", type any}}),
				    #"Removed Top Rows" = Table.Skip(#"Changed Type",1),
				    #"Unpivoted Other Columns" = Table.UnpivotOtherColumns(#"Removed Top Rows", {"Ops Team Currency"}, "Attribute", "Value"),
				    #"Renamed Columns" = Table.RenameColumns(#"Unpivoted Other Columns",{{"Ops Team Currency", "Date"}, {"Attribute", "Ops Team Currency"}, {"Value", "Queue Input Count"}}),
				    #"Changed Type1" = Table.TransformColumnTypes(#"Renamed Columns",{{"Queue Input Count", Int64.Type}, {"Date", type date}})
				in
				    #"Changed Type1"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

